# © 2019 Netxillon Technologies.
# ------------------------------
# Author: Gurmukh Singh
# Email: trainings@netxillon.com
# Date: 22-06-2020
# ------------------------------

# You are free to use these as long as you acknowledge it back to the source and give due credit.

# ****************************************WARNING************************
# There is no guarantee for the use of these scripts/roles and the author
# is in no way liable for any damange caused by the use of these scripts.
# ************************************************************************
---
- name:              Install HAproxy Server
  yum:               name={{item}}
  with_items:
    - haproxy

- name:      Copy my.cnf file
  template:
    src:     haproxy.cfg
    dest:    /etc/haproxy/haproxy.cfg
    owner:   root
    group:   root
    mode:    0644

- name: Start HAproxy Server
  ignore_errors: yes
  service: name=haproxy state=restarted enabled=yes
